version: "3"
services:
  nginx:
    image:  nginx:alpine
    ports:
    - 80:80
    volumes:
    - /home/docker/html:/usr/share/nginx/html
    - /home/docker/conf/nginx.conf:/etc/nginx/nginx.conf
  php:
    image:  devilbox/php-fpm:5.2-work-0.89
    volumes:
    - /home/docker/html:/var/www/html
  mysql:
    image:  mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=123456
